# Generated by Django 4.1.2 on 2022-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_articles_content_alter_articles_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="author",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
